services:
  - type: web
    name: bharat-wealth-backend
    plan: free
    runtime: docker
    dockerfilePath: ./bankend/Dockerfile
    dockerContext: ./bankend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bharat-wealth-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: bharat-wealth-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: bharat-wealth-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: AUDIT_HMAC_KEY
        generateValue: true
      - key: ML_SERVICE_URL
        value: https://bharataiwealth.onrender.com
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  - type: web
    name: bharat-wealth-ml
    plan: free
    runtime: docker
    dockerfilePath: ./ml-service/Dockerfile
    dockerContext: ./ml-service
    envVars:
      - key: BACKEND_URL
        value: https://bharataiwealth.onrender.com
      - key: FRONTEND_URL
        value: https://bharataiwealth-blush.vercel.app
      - key: PYTHONUNBUFFERED
        value: "1"

databases:
  - name: bharat-wealth-db
    plan: free
    databaseName: wealthdb
    user: bharatuser
